# Generated by Django 4.2.30 on 2026-07-18 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzil')),
                ('kompaniya', models.CharField(blank=True, max_length=200, verbose_name='Kompaniya')),
                ('mavzu', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('xabar', models.TextField(verbose_name='Xabar')),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ("o'qilgan", "O'qilgan"), ('javob_berildi', 'Javob berildi')], default='yangi', max_length=20, verbose_name='Holat')),
                ('email_yuborildi', models.BooleanField(default=False, verbose_name='Email yuborildi')),
                ('telegram_yuborildi', models.BooleanField(default=False, verbose_name='Telegram yuborildi')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=100, verbose_name='Familiya')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email manzil')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqam')),
                ('tugilgan_sana', models.DateField(blank=True, null=True, verbose_name='Tugilgan sana')),
                ('haqida', models.TextField(blank=True, verbose_name='Haqida')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profil rasmi')),
                ('github_username', models.CharField(blank=True, max_length=100, verbose_name='GitHub username')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram username')),
                ('joylashuv', models.CharField(blank=True, max_length=200, verbose_name='Joylashuv')),
                ('malaka', models.CharField(blank=True, max_length=200, verbose_name='Malaka')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
                'ordering': ['-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('tavsif', models.TextField(verbose_name='Tavsif')),
                ('qisqa_tavsif', models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Loyiha rasmi')),
                ('github_link', models.URLField(blank=True, verbose_name='GitHub link')),
                ('live_link', models.URLField(blank=True, verbose_name='Live demo link')),
                ('tech_stack', models.CharField(help_text='Texnologiyalar vergul bilan ajratilgan', max_length=500, verbose_name='Tech stack')),
                ('kategoriya', models.CharField(blank=True, max_length=100, verbose_name='Kategoriya')),
                ('manba', models.CharField(choices=[('manual', "Qo'lda qo'shilgan"), ('github', 'GitHub API dan')], default='manual', max_length=20, verbose_name='Manba')),
                ('github_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='GitHub ID')),
                ('stars', models.IntegerField(default=0, verbose_name='Yulduzlar soni')),
                ('forks', models.IntegerField(default=0, verbose_name='Fork lar soni')),
                ('til', models.CharField(blank=True, max_length=50, verbose_name='Asosiy til')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol loyiha')),
                ('tartib_raqam', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['tartib_raqam', '-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayt_nomi', models.CharField(default='Portfolio', max_length=200, verbose_name='Sayt nomi')),
                ('sayt_tavsifi', models.TextField(blank=True, verbose_name='Sayt tavsifi')),
                ('footer_matni', models.TextField(blank=True, verbose_name='Footer matni')),
                ('copyright_matni', models.CharField(blank=True, max_length=200, verbose_name='Copyright matni')),
                ('Aktiv', models.BooleanField(default=True, verbose_name='Faol')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamasi',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('tartib_raqam', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Ko'nikma kategoriyasi",
                'verbose_name_plural': "Ko'nikma kategoriyalari",
                'ordering': ['tartib_raqam'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name="Ko'nikma nomi")),
                ('daraja', models.CharField(choices=[('boshlangich', "Boshlang'ich"), ('orta', "O'rta"), ('yukori', 'Yuqori'), ('expert', 'Ekspert')], default='orta', max_length=20, verbose_name='Daraja')),
                ('foiz', models.IntegerField(default=50, help_text='0-100 orasida daraja foizi', verbose_name='Daraja foizi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='skills/', verbose_name='Logo rasm')),
                ('tartib_raqam', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.skillcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
                'ordering': ['kategoriya', 'tartib_raqam'],
            },
        ),
    ]
